# Generated by Django 6.0 on 2025-12-24 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_category_task_status_habit_reminder'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='progress',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reminder',
            name='date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
